// ZotMoov
// prefs.js
// Author: Khodami Aaron

pref('extensions.zotmoov.dst_dir', '');
pref('extensions.zotmoov.attach_search_dir', '');
pref('extensions.zotmoov.enable_automove', true);
pref('extensions.zotmoov.enable_subdir_move', false);
pref('extensions.zotmoov.file_behavior', 'move');
pref('extensions.zotmoov.subdirectory_string', '{%c}');
pref('extensions.zotmoov.auto_process_delay', 5000);
pref('extensions.zotmoov.copy_group_libraries', true)
pref('extensions.zotmoov.allowed_fileext', JSON.stringify(['pdf', 'epub', 'docx', 'djvu']))
pref('extensions.zotmoov.delete_files', false);
pref('extensions.zotmoov.prune_empty_dir', true);
pref('extensions.zotmoov.enable_attach_dir', false);
pref('extensions.zotmoov.rename_title', true);
pref('extensions.zotmoov.undefined_str', 'undefined');
pref('extensions.zotmoov.cwc_commands', JSON.stringify({}));
pref('extensions.zotmoov.keys.move_item', '');
pref('extensions.zotmoov.keys.move_item_custom_dir', '');
pref('extensions.zotmoov.keys.link_item', '');
pref('extensions.zotmoov.keys.convert_linked', '');
pref('extensions.zotmoov.menu_items.move.hidden', false);
pref('extensions.zotmoov.menu_items.convert_linked.hidden', false);
pref('extensions.zotmoov.menu_items.custom_move.hidden', false);
pref('extensions.zotmoov.menu_items.fix_note_links.hidden', true);
pref('extensions.zotmoov.custom_menu_items', JSON.stringify({}));
pref('extensions.zotmoov.add_zotmoov_tag', true);
pref('extensions.zotmoov.tag_str', 'zotgit');
pref('extensions.zotmoov.attach_prompt', false);
pref('extensions.zotmoov.process_synced_files', false);
pref('extensions.zotmoov.max_io_concurrency', 1);
pref('extensions.zotmoov.strip_diacritics', false);
pref('extensions.zotmoov.sync.github.enabled', false);
pref('extensions.zotmoov.sync.github.repository', '');
pref('extensions.zotmoov.sync.github.repository_backup', '');
pref('extensions.zotmoov.sync.github.branch', 'main');
pref('extensions.zotmoov.sync.github.filepath', 'zotgit-settings.json');
pref('extensions.zotmoov.sync.github.token', '');
pref('extensions.zotmoov.sync.github.auto_pull', true);
pref('extensions.zotmoov.sync.github.auto_push', false);
pref('extensions.zotmoov.sync.github.sync_pdfs', true);
pref('extensions.zotmoov.sync.github.pdf_root', 'pdfs');
pref('extensions.zotmoov.sync.github.remote_pdf_mode', false);
pref('extensions.zotmoov.sync.github.last_remote_sha', '');
pref('extensions.zotmoov.sync.github.last_sync_time', 0);